POST http://localhost:8080/api/stock
Content-Type: application/json

{
    "symbol": "GE",
    "tags": [
        "aerospace",
        "manufacturing",
        "defense"
    ],
    "relatedStocks": [
        "BA",
        "RTX",
        "LMT",
        "GD"
    ]
}

# GET http://localhost:8080/api/stock
