POST http://localhost:8080/api/stock
Content-Type: application/json

{
    "symbol": "EEEE",
    "tags": [
        "technology"
    ],
    "relatedStocks": [
        "AAPL"
    ]
}

# GET http://localhost:8080/api/stock
