POST http://localhost:8080/api/stock
Content-Type: application/json

{
    "symbol": "AJAXZZZZZZZZZZZZZZ",
    "tags": [
        {
            "name": "technology"
        }
    ],
    "stocks": [
        {
            "symbol": "AAPL"
        }
    ]
}